//get rid of mime type as any file uploaded

import { AbstractControl } from '@angular/forms';
import { Observable, Observer, of } from 'rxjs';

export const mimeType = (
  control: AbstractControl
): Promise<{ [key: string]: any }> | Observable<{ [key: string]: any }> => {
  if (typeof(control.value) === 'string') {
    return of(null);
  }
  const file = control.value as File;
  const fileReader = new FileReader();
  const frObs = Observable.create(
    (observer: Observer<{ [key: string]: any }>) => {
      fileReader.addEventListener('loadend', () => {
        const arr = new Uint8Array(fileReader.result as ArrayBuffer).subarray(0, 4);
        let header = '';
        let isValid = false;
        for (let i = 0; i < arr.length; i++) {
          header += arr[i].toString(16);
        }
        switch (header) {
          case '89504e47':
            isValid = true;
            break;
          case 'ffd8ffe0':
          case 'ffd8ffe1':
          case 'ffd8ffe2':
          case 'ffd8ffe3':
          case 'ffd8ffe8':
          case 'D0CF11E0A1B11AE1':
          case '3dm':
          case '3dmf':
          case 'a':
          case 'aab':
          case 'aam':
          case 'aas':
          case 'abc':
          case 'acgi':
          case 'afl':
          case 'ai':
          case 'aif':
          case 'aif':
          case 'aifc':
          case 'aifc':
          case 'aiff':
          case 'aiff':
          case 'aim':
          case 'aip':
          case 'ani':
          case 'aos':
          case 'aps':
          case 'arc':
          case 'arj':
          case 'arj':
          case 'art':
          case 'asf':
          case 'asm':
          case 'asp':
          case 'asx':
          case 'asx':
          case 'asx':
          case 'au':
          case 'au':
          case 'avi':
          case 'avi':
          case 'avi':
          case 'avi':
          case 'avs':
          case 'bcpi':
          case 'bin':
          case 'bin':
          case 'bin':
          case 'bin':
          case 'bin':
          case 'bm':
          case 'bmp':
          case 'bmp':
          case 'boo':
          case 'book':
          case 'boz':
          case 'bsh':
          case 'bz':
          case 'bz2':
          case 'c':
          case 'c':
          case 'c++':
          case 'cat':
          case 'cc':
          case 'cc':
          case 'ccad':
          case 'cco':
          case 'cdf':
          case 'cdf':
          case 'cdf':
          case 'cer':
          case 'cer':
          case 'cha':
          case 'chat':
          case 'clas':
          case 'clas':
          case 'clas':
          case 'com':
          case 'com':
          case 'conf':
          case 'cpio':
          case 'cpp':
          case 'cpt':
          case 'cpt':
          case 'cpt':
          case 'crl':
          case 'crl':
          case 'crt':
          case 'crt':
          case 'crt':
          case 'csh':
          case 'csh':
          case 'css':
          case 'css':
          case 'cxx':
          case 'dcr':
          case 'deep':
          case 'def':
          case 'der':
          case 'dif':
          case 'dir':
          case 'dl':
          case 'dl':
          case 'doc':
          case 'docx':
          case 'dot':
          case 'dp':
          case 'drw':
          case 'dump':
          case 'dv':
          case 'dvi':
          case 'dwf':
          case 'dwf':
          case 'dwg':
          case 'dwg':
          case 'dwg':
          case 'dxf':
          case 'dxf':
          case 'dxf':
          case 'dxr':
          case 'el':
          case 'elc':
          case 'elc':
          case 'env':
          case 'eps':
          case 'es':
          case 'etx':
          case 'evy':
          case 'evy':
          case 'exe':
          case 'f':
          case 'f':
          case 'f77':
          case 'f90':
          case 'f90':
          case 'fdf':
          case 'fif':
          case 'fif':
          case 'fli':
          case 'fli':
          case 'flo':
          case 'flx':
          case 'fmf':
          case 'for':
          case 'for':
          case 'fpx':
          case 'fpx':
          case 'frl':
          case 'funk':
          case 'g':
          case 'g3':
          case 'gif':
          case 'gl':
          case 'gl':
          case 'gsd':
          case 'gsm':
          case 'gsp':
          case 'gss':
          case 'gtar':
          case 'gz':
          case 'gz':
          case 'gzip':
          case 'gzip':
          case 'h':
          case 'h':
          case 'hdf':
          case 'help':
          case 'hgl':
          case 'hh':
          case 'hh':
          case 'hlb':
          case 'hlp':
          case 'hlp':
          case 'hlp':
          case 'hpg':
          case 'hpgl':
          case 'hqx':
          case 'hqx':
          case 'hqx':
          case 'hqx':
          case 'hqx':
          case 'hqx':
          case 'hta':
          case 'htc':
          case 'htm':
          case 'html':
          case 'html':
          case 'htt':
          case 'htx':
          case 'ice':
          case 'ico':
          case 'idc':
          case 'ief':
          case 'iefs':
          case 'iges':
          case 'iges':
          case 'igs':
          case 'igs':
          case 'ima':
          case 'imap':
          case 'inf':
          case 'ins':
          case 'ip':
          case 'isu':
          case 'it':
          case 'iv':
          case 'ivr':
          case 'ivy':
          case 'jam':
          case 'jav':
          case 'jav':
          case 'java':
          case 'java':
          case 'jcm':
          case 'jfif':
          case 'jfif':
          case 'jfif-tbnl':
          case 'jpe':
          case 'jpe':
          case 'jpeg':
          case 'jpeg':
          case 'jpg':
          case 'jpg':
          case 'jps':
          case 'js':
          case 'js':
          case 'js':
          case 'js':
          case 'js':
          case 'jut':
          case 'kar':
          case 'kar':
          case 'ksh':
          case 'ksh':
          case 'la':
          case 'la':
          case 'lam':
          case 'late':
          case 'lha':
          case 'lha':
          case 'lha':
          case 'lhx':
          case 'list':
          case 'lma':
          case 'lma':
          case 'log':
          case 'lsp':
          case 'lsp':
          case 'lst':
          case 'lsx':
          case 'ltx':
          case 'lzh':
          case 'lzh':
          case 'lzx':
          case 'lzx':
          case 'lzx':
          case 'm':
          case 'm':
          case 'm1v':
          case 'm2a':
          case 'm2v':
          case 'm3u':
          case 'man':
          case 'map':
          case 'mar':
          case 'mbd':
          case 'mc$':
          case 'mcd':
          case 'mcd':
          case 'mcf':
          case 'mcf':
          case 'mcp':
          case 'me':
          case 'mht':
          case 'mhtm':
          case 'mid':
          case 'mid':
          case 'mid':
          case 'mid':
          case 'mid':
          case 'mid':
          case 'midi':
          case 'midi':
          case 'midi':
          case 'midi':
          case 'midi':
          case 'midi':
          case 'mif':
          case 'mif':
          case 'mime':
          case 'mime':
          case 'mjf':
          case 'mjpg':
          case 'mm':
          case 'mm':
          case 'mme':
          case 'mod':
          case 'mod':
          case 'moov':
          case 'mov':
          case 'movi':
          case 'mp2':
          case 'mp2':
          case 'mp2':
          case 'mp2':
          case 'mp2':
          case 'mp3':
          case 'mp3':
          case 'mp3':
          case 'mp3':
          case 'mpa':
          case 'mpa':
          case 'mpc':
          case 'mpe':
          case 'mpeg':
          case 'mpg':
          case 'mpg':
          case 'mpga':
          case 'mpp':
          case 'mpt':
          case 'mpv':
          case 'mpx':
          case 'mrc':
          case 'ms':
          case 'mv':
          case 'my':
          case 'mzz':
          case 'nap':
          case 'napl':
          case 'nc':
          case 'ncm':
          case 'nif':
          case 'niff':
          case 'nix':
          case 'nsc':
          case 'nvd':
          case 'o':
          case 'oda':
          case 'omc':
          case 'omcd':
          case 'omcr':
          case 'p':
          case 'p10':
          case 'p10':
          case 'p12':
          case 'p12':
          case 'p7a':
          case 'p7c':
          case 'p7c':
          case 'p7m':
          case 'p7m':
          case 'p7r':
          case 'p7s':
          case 'part':
          case 'pas':
          case 'pbm':
          case 'pcl':
          case 'pcl':
          case 'pct':
          case 'pcx':
          case 'pdb':
          case 'pdf':
          case 'pfun':
          case 'pfun':
          case 'pgm':
          case 'pgm':
          case 'pic':
          case 'pict':
          case 'pkg':
          case 'pko':
          case 'pl':
          case 'pl':
          case 'plx':
          case 'pm':
          case 'pm':
          case 'pm4':
          case 'pm5':
          case 'png':
          case 'pnm':
          case 'pnm':
          case 'pot':
          case 'pot':
          case 'pov':
          case 'ppa':
          case 'ppm':
          case 'pps':
          case 'pps':
          case 'ppt':
          case 'ppt':
          case 'ppt':
          case 'ppt':
          case 'ppz':
          case 'pre':
          case 'prt':
          case 'ps':
          case 'psd':
          case 'pvu':
          case 'pwz':
          case 'py':
          case 'pyc':
          case 'qcp':
          case 'qd3':
          case 'qd3d':
          case 'qif':
          case 'qt':
          case 'qtc':
          case 'qti':
          case 'qtif':
          case 'ra':
          case 'ra':
          case 'ra':
          case 'ram':
          case 'ras':
          case 'ras':
          case 'ras':
          case 'rast':
          case 'rexx':
          case 'rf':
          case 'rgb':
          case 'rm':
          case 'rm':
          case 'rmi':
          case 'rmm':
          case 'rmp':
          case 'rmp':
          case 'rng':
          case 'rng':
          case 'rnx':
          case 'roff':
          case 'rp':
          case 'rpm':
          case 'rt':
          case 'rt':
          case 'rtf':
          case 'rtf':
          case 'rtf':
          case 'rtx':
          case 'rtx':
          case 'rv':
          case 's':
          case 's3m':
          case 'save':
          case 'sbk':
          case 'scm':
          case 'scm':
          case 'scm':
          case 'scm':
          case 'sdml':
          case 'sdp':
          case 'sdp':
          case 'sdr':
          case 'sea':
          case 'sea':
          case 'set':
          case 'sgm':
          case 'sgm':
          case 'sgml':
          case 'sgml':
          case 'sh':
          case 'sh':
          case 'sh':
          case 'sh':
          case 'shar':
          case 'shar':
          case 'shtm':
          case 'shtm':
          case 'sid':
          case 'sit':
          case 'sit':
          case 'skd':
          case 'skm':
          case 'skp':
          case 'skt':
          case 'sl':
          case 'smi':
          case 'smil':
          case 'snd':
          case 'snd':
          case 'sol':
          case 'spc':
          case 'spc':
          case 'spl':
          case 'spr':
          case 'spri':
          case 'src':
          case 'ssi':
          case 'ssm':
          case 'sst':
          case 'step':
          case 'stl':
          case 'stl':
          case 'stl':
          case 'stp':
          case 'sv4c':
          case 'sv4c':
          case 'svf':
          case 'svf':
          case 'svr':
          case 'svr':
          case 'swf':
          case 't':
          case 'talk':
          case 'tar':
          case 'tbk':
          case 'tbk':
          case 'tcl':
          case 'tcl':
          case 'tcsh':
          case 'tex':
          case 'texi':
          case 'texi':
          case 'text':
          case 'text':
          case 'tgz':
          case 'tgz':
          case 'tif':
          case 'tif':
          case 'tiff':
          case 'tiff':
          case 'tr':
          case 'tsi':
          case 'tsp':
          case 'tsp':
          case 'tsv':
          case 'turb':
          case 'txt':
          case 'uil':
          case 'uni':
          case 'unis':
          case 'unv':
          case 'uri':
          case 'uris':
          case 'usta':
          case 'usta':
          case 'uu':
          case 'uu':
          case 'uue':
          case 'vcd':
          case 'vcs':
          case 'vda':
          case 'vdo':
          case 'vew':
          case 'viv':
          case 'viv':
          case 'vivo':
          case 'vivo':
          case 'vmd':
          case 'vmf':
          case 'voc':
          case 'voc':
          case 'vos':
          case 'vox':
          case 'vqe':
          case 'vqf':
          case 'vql':
          case 'vrml':
          case 'vrml':
          case 'vrml':
          case 'vrt':
          case 'vsd':
          case 'vst':
          case 'vsw':
          case 'w60':
          case 'w61':
          case 'w6w':
          case 'wav':
          case 'wav':
          case 'wb1':
          case 'wbmp':
          case 'web':
          case 'wiz':
          case 'wk1':
          case 'wmf':
          case 'wml':
          case 'wmlc':
          case 'wmls':
          case 'wmls':
          case 'word':
          case 'wp':
          case 'wp5':
          case 'wp5':
          case 'wp6':
          case 'wpd':
          case 'wpd':
          case 'wq1':
          case 'wri':
          case 'wri':
          case 'wrl':
          case 'wrl':
          case 'wrl':
          case 'wrz':
          case 'wrz':
          case 'wsc':
          case 'wsrc':
          case 'wtk':
          case 'xbm':
          case 'xbm':
          case 'xbm':
          case 'xdr':
          case 'xgz':
          case 'xif':
          case 'xl':
          case 'xla':
          case 'xla':
          case 'xla':
          case 'xlb':
          case 'xlb':
          case 'xlb':
          case 'xlc':
          case 'xlc':
          case 'xlc':
          case 'xld':
          case 'xld':
          case 'xlk':
          case 'xlk':
          case 'xll':
          case 'xll':
          case 'xll':
          case 'xlm':
          case 'xlm':
          case 'xlm':
          case 'xls':
          case 'xls':
          case 'xls':
          case 'xls':
          case 'xlt':
          case 'xlt':
          case 'xlv':
          case 'xlv':
          case 'xlw':
          case 'xlw':
          case 'xlw':
          case 'xlw':
          case 'xm':
          case 'xml':
          case 'xml':
          case 'xmz':
          case 'xpix':
          case 'xpm':
          case 'xpm':
          case 'x-png':
          case 'xsr':
          case 'xwd':
          case 'xwd':
          case 'xyz':
          case 'z':
          case 'z':
          case 'zip':
          case 'zip':
          case 'zip':
          case 'zip':
          case 'zoo':
          case 'zsh':
          case 'x-world/x-3dmf':
          case 'x-world/x-3dmf':
          case 'application/octet-stream':
          case 'application/x-authorware-bin':
          case 'application/x-authorware-map':
          case 'application/x-authorware-seg':
          case 'text/vnd.abc':
          case 'text/html':
          case 'video/animaflex':
          case 'application/postscript':
          case 'audio/aiff':
          case 'audio/x-aiff':
          case 'audio/aiff':
          case 'audio/x-aiff':
          case 'audio/aiff':
          case 'audio/x-aiff':
          case 'application/x-aim':
          case 'text/x-audiosoft-intra':
          case 'application/x-navi-animation':
          case 'application/x-nokia-9000-communicator-add-on-software':
          case 'application/mime':
          case 'application/octet-stream':
          case 'application/arj':
          case 'application/octet-stream':
          case 'image/x-jg':
          case 'video/x-ms-asf':
          case 'text/x-asm':
          case 'text/asp':
          case 'application/x-mplayer2':
          case 'video/x-ms-asf':
          case 'video/x-ms-asf-plugin':
          case 'audio/basic':
          case 'audio/x-au':
          case 'application/x-troff-msvideo':
          case 'video/avi':
          case 'video/msvideo':
          case 'video/x-msvideo':
          case 'video/avs-video':
          case 'application/x-bcpio':
          case 'application/mac-binary':
          case 'application/macbinary':
          case 'application/octet-stream':
          case 'application/x-binary':
          case 'application/x-macbinary':
          case 'image/bmp':
          case 'image/bmp':
          case 'image/x-windows-bmp':
          case 'application/book':
          case 'application/book':
          case 'application/x-bzip2':
          case 'application/x-bsh':
          case 'application/x-bzip':
          case 'application/x-bzip2':
          case 'text/plain':
          case 'text/x-c':
          case 'text/plain':
          case 'application/vnd.ms-pki.seccat':
          case 'text/plain':
          case 'text/x-c':
          case 'application/clariscad':
          case 'application/x-cocoa':
          case 'application/cdf':
          case 'application/x-cdf':
          case 'application/x-netcdf':
          case 'application/pkix-cert':
          case 'application/x-x509-ca-cert':
          case 'application/x-chat':
          case 'application/x-chat':
          case 'application/java':
          case 'application/java-byte-code':
          case 'application/x-java-class':
          case 'application/octet-stream':
          case 'text/plain':
          case 'text/plain':
          case 'application/x-cpio':
          case 'text/x-c':
          case 'application/mac-compactpro':
          case 'application/x-compactpro':
          case 'application/x-cpt':
          case 'application/pkcs-crl':
          case 'application/pkix-crl':
          case 'application/pkix-cert':
          case 'application/x-x509-ca-cert':
          case 'application/x-x509-user-cert':
          case 'application/x-csh':
          case 'text/x-script.csh':
          case 'application/x-pointplus':
          case 'text/css':
          case 'text/plain':
          case 'application/x-director':
          case 'application/x-deepv':
          case 'text/plain':
          case 'application/x-x509-ca-cert':
          case 'video/x-dv':
          case 'application/x-director':
          case 'video/dl':
          case 'video/x-dl':
          case 'application/msword':
          case 'application/msword':
          case 'application/commonground':
          case 'application/drafting':
          case 'application/octet-stream':
          case 'video/x-dv':
          case 'application/x-dvi':
          case 'drawing/x-dwf (old)':
          case 'model/vnd.dwf':
          case 'application/acad':
          case 'image/vnd.dwg':
          case 'image/x-dwg':
          case 'application/dxf':
          case 'image/vnd.dwg':
          case 'image/x-dwg':
          case 'application/x-director':
          case 'text/x-script.elisp':
          case 'application/x-bytecode.elisp (compiled elisp)':
          case 'application/x-elc':
          case 'application/x-envoy':
          case 'application/postscript':
          case 'application/x-esrehber':
          case 'text/x-setext':
          case 'application/envoy':
          case 'application/x-envoy':
          case 'application/octet-stream':
          case 'text/plain':
          case 'text/x-fortran':
          case 'text/x-fortran':
          case 'text/plain':
          case 'text/x-fortran':
          case 'application/vnd.fdf':
          case 'application/fractals':
          case 'image/fif':
          case 'video/fli':
          case 'video/x-fli':
          case 'image/florian':
          case 'text/vnd.fmi.flexstor':
          case 'video/x-atomic3d-feature':
          case 'text/plain':
          case 'text/x-fortran':
          case 'image/vnd.fpx':
          case 'image/vnd.net-fpx':
          case 'application/freeloader':
          case 'audio/make':
          case 'text/plain':
          case 'image/g3fax':
          case 'image/gif':
          case 'video/gl':
          case 'video/x-gl':
          case 'audio/x-gsm':
          case 'audio/x-gsm':
          case 'application/x-gsp':
          case 'application/x-gss':
          case 'application/x-gtar':
          case 'application/x-compressed':
          case 'application/x-gzip':
          case 'application/x-gzip':
          case 'multipart/x-gzip':
          case 'text/plain':
          case 'text/x-h':
          case 'application/x-hdf':
          case 'application/x-helpfile':
          case 'application/vnd.hp-hpgl':
          case 'text/plain':
          case 'text/x-h':
          case 'text/x-script':
          case 'application/hlp':
          case 'application/x-helpfile':
          case 'application/x-winhelp':
          case 'application/vnd.hp-hpgl':
          case 'application/vnd.hp-hpgl':
          case 'application/binhex':
          case 'application/binhex4':
          case 'application/mac-binhex':
          case 'application/mac-binhex40':
          case 'application/x-binhex40':
          case 'application/x-mac-binhex40':
          case 'application/hta':
          case 'text/x-component':
          case 'text/html':
          case 'text/html':
          case 'text/html':
          case 'text/webviewhtml':
          case 'text/html':
          case 'x-conference/x-cooltalk':
          case 'image/x-icon':
          case 'text/plain':
          case 'image/ief':
          case 'image/ief':
          case 'application/iges':
          case 'model/iges':
          case 'application/iges':
          case 'model/iges':
          case 'application/x-ima':
          case 'application/x-httpd-imap':
          case 'application/inf':
          case 'application/x-internett-signup':
          case 'application/x-ip2':
          case 'video/x-isvideo':
          case 'audio/it':
          case 'application/x-inventor':
          case 'i-world/i-vrml':
          case 'application/x-livescreen':
          case 'audio/x-jam':
          case 'text/plain':
          case 'text/x-java-source':
          case 'text/plain':
          case 'text/x-java-source':
          case 'application/x-java-commerce':
          case 'image/jpeg':
          case 'image/pjpeg':
          case 'image/jpeg':
          case 'image/jpeg':
          case 'image/pjpeg':
          case 'image/jpeg':
          case 'image/pjpeg':
          case 'image/jpeg':
          case 'image/pjpeg':
          case 'image/x-jps':
          case 'application/x-javascript':
          case 'application/javascript':
          case 'application/ecmascript':
          case 'text/javascript':
          case 'text/ecmascript':
          case 'image/jutvision':
          case 'audio/midi':
          case 'music/x-karaoke':
          case 'application/x-ksh':
          case 'text/x-script.ksh':
          case 'audio/nspaudio':
          case 'audio/x-nspaudio':
          case 'audio/x-liveaudio':
          case 'application/x-latex':
          case 'application/lha':
          case 'application/octet-stream':
          case 'application/x-lha':
          case 'application/octet-stream':
          case 'text/plain':
          case 'audio/nspaudio':
          case 'audio/x-nspaudio':
          case 'text/plain':
          case 'application/x-lisp':
          case 'text/x-script.lisp':
          case 'text/plain':
          case 'text/x-la-asf':
          case 'application/x-latex':
          case 'application/octet-stream':
          case 'application/x-lzh':
          case 'application/lzx':
          case 'application/octet-stream':
          case 'application/x-lzx':
          case 'text/plain':
          case 'text/x-m':
          case 'video/mpeg':
          case 'audio/mpeg':
          case 'video/mpeg':
          case 'audio/x-mpequrl':
          case 'application/x-troff-man':
          case 'application/x-navimap':
          case 'text/plain':
          case 'application/mbedlet':
          case 'application/x-magic-cap-package-1.0':
          case 'application/mcad':
          case 'application/x-mathcad':
          case 'image/vasa':
          case 'text/mcf':
          case 'application/netmc':
          case 'application/x-troff-me':
          case 'message/rfc822':
          case 'message/rfc822':
          case 'application/x-midi':
          case 'audio/midi':
          case 'audio/x-mid':
          case 'audio/x-midi':
          case 'music/crescendo':
          case 'x-music/x-midi':
          case 'application/x-midi':
          case 'audio/midi':
          case 'audio/x-mid':
          case 'audio/x-midi':
          case 'music/crescendo':
          case 'x-music/x-midi':
          case 'application/x-frame':
          case 'application/x-mif':
          case 'message/rfc822':
          case 'www/mime':
          case 'audio/x-vnd.audioexplosion.mjuicemediafile':
          case 'video/x-motion-jpeg':
          case 'application/base64':
          case 'application/x-meme':
          case 'application/base64':
          case 'audio/mod':
          case 'audio/x-mod':
          case 'video/quicktime':
          case 'video/quicktime':
          case 'video/x-sgi-movie':
          case 'audio/mpeg':
          case 'audio/x-mpeg':
          case 'video/mpeg':
          case 'video/x-mpeg':
          case 'video/x-mpeq2a':
          case 'audio/mpeg3':
          case 'audio/x-mpeg-3':
          case 'video/mpeg':
          case 'video/x-mpeg':
          case 'audio/mpeg':
          case 'video/mpeg':
          case 'application/x-project':
          case 'video/mpeg':
          case 'video/mpeg':
          case 'audio/mpeg':
          case 'video/mpeg':
          case 'audio/mpeg':
          case 'application/vnd.ms-project':
          case 'application/x-project':
          case 'application/x-project':
          case 'application/x-project':
          case 'application/marc':
          case 'application/x-troff-ms':
          case 'video/x-sgi-movie':
          case 'audio/make':
          case 'application/x-vnd.audioexplosion.mzz':
          case 'image/naplps':
          case 'image/naplps':
          case 'application/x-netcdf':
          case 'application/vnd.nokia.configuration-message':
          case 'image/x-niff':
          case 'image/x-niff':
          case 'application/x-mix-transfer':
          case 'application/x-conference':
          case 'application/x-navidoc':
          case 'application/octet-stream':
          case 'application/oda':
          case 'application/x-omc':
          case 'application/x-omcdatamaker':
          case 'application/x-omcregerator':
          case 'text/x-pascal':
          case 'application/pkcs10':
          case 'application/x-pkcs10':
          case 'application/pkcs-12':
          case 'application/x-pkcs12':
          case 'application/x-pkcs7-signature':
          case 'application/pkcs7-mime':
          case 'application/x-pkcs7-mime':
          case 'application/pkcs7-mime':
          case 'application/x-pkcs7-mime':
          case 'application/x-pkcs7-certreqresp':
          case 'application/pkcs7-signature':
          case 'application/pro_eng':
          case 'text/pascal':
          case 'image/x-portable-bitmap':
          case 'application/vnd.hp-pcl':
          case 'application/x-pcl':
          case 'image/x-pict':
          case 'image/x-pcx':
          case 'chemical/x-pdb':
          case 'application/pdf':
          case 'audio/make':
          case 'audio/make.my.funk':
          case 'image/x-portable-graymap':
          case 'image/x-portable-greymap':
          case 'image/pict':
          case 'image/pict':
          case 'application/x-newton-compatible-pkg':
          case 'application/vnd.ms-pki.pko':
          case 'text/plain':
          case 'text/x-script.perl':
          case 'application/x-pixclscript':
          case 'image/x-xpixmap':
          case 'text/x-script.perl-module':
          case 'application/x-pagemaker':
          case 'application/x-pagemaker':
          case 'image/png':
          case 'application/x-portable-anymap':
          case 'image/x-portable-anymap':
          case 'application/mspowerpoint':
          case 'application/vnd.ms-powerpoint':
          case 'model/x-pov':
          case 'application/vnd.ms-powerpoint':
          case 'image/x-portable-pixmap':
          case 'application/mspowerpoint':
          case 'application/vnd.ms-powerpoint':
          case 'application/mspowerpoint':
          case 'application/powerpoint':
          case 'application/vnd.ms-powerpoint':
          case 'application/x-mspowerpoint':
          case 'application/mspowerpoint':
          case 'application/x-freelance':
          case 'application/pro_eng':
          case 'application/postscript':
          case 'application/octet-stream':
          case 'paleovu/x-pv':
          case 'application/vnd.ms-powerpoint':
          case 'text/x-script.phyton':
          case 'application/x-bytecode.python':
          case 'audio/vnd.qcelp':
          case 'x-world/x-3dmf':
          case 'x-world/x-3dmf':
          case 'image/x-quicktime':
          case 'video/quicktime':
          case 'video/x-qtc':
          case 'image/x-quicktime':
          case 'image/x-quicktime':
          case 'audio/x-pn-realaudio':
          case 'audio/x-pn-realaudio-plugin':
          case 'audio/x-realaudio':
          case 'audio/x-pn-realaudio':
          case 'application/x-cmu-raster':
          case 'image/cmu-raster':
          case 'image/x-cmu-raster':
          case 'image/cmu-raster':
          case 'text/x-script.rexx':
          case 'image/vnd.rn-realflash':
          case 'image/x-rgb':
          case 'application/vnd.rn-realmedia':
          case 'audio/x-pn-realaudio':
          case 'audio/mid':
          case 'audio/x-pn-realaudio':
          case 'audio/x-pn-realaudio':
          case 'audio/x-pn-realaudio-plugin':
          case 'application/ringing-tones':
          case 'application/vnd.nokia.ringing-tone':
          case 'application/vnd.rn-realplayer':
          case 'application/x-troff':
          case 'image/vnd.rn-realpix':
          case 'audio/x-pn-realaudio-plugin':
          case 'text/richtext':
          case 'text/vnd.rn-realtext':
          case 'application/rtf':
          case 'application/x-rtf':
          case 'text/richtext':
          case 'application/rtf':
          case 'text/richtext':
          case 'video/vnd.rn-realvideo':
          case 'text/x-asm':
          case 'audio/s3m':
          case 'application/octet-stream':
          case 'application/x-tbook':
          case 'application/x-lotusscreencam':
          case 'text/x-script.guile':
          case 'text/x-script.scheme':
          case 'video/x-scm':
          case 'text/plain':
          case 'application/sdp':
          case 'application/x-sdp':
          case 'application/sounder':
          case 'application/sea':
          case 'application/x-sea':
          case 'application/set':
          case 'text/sgml':
          case 'text/x-sgml':
          case 'text/sgml':
          case 'text/x-sgml':
          case 'application/x-bsh':
          case 'application/x-sh':
          case 'application/x-shar':
          case 'text/x-script.sh':
          case 'application/x-bsh':
          case 'application/x-shar':
          case 'text/html':
          case 'text/x-server-parsed-html':
          case 'audio/x-psid':
          case 'application/x-sit':
          case 'application/x-stuffit':
          case 'application/x-koan':
          case 'application/x-koan':
          case 'application/x-koan':
          case 'application/x-koan':
          case 'application/x-seelogo':
          case 'application/smil':
          case 'application/smil':
          case 'audio/basic':
          case 'audio/x-adpcm':
          case 'application/solids':
          case 'application/x-pkcs7-certificates':
          case 'text/x-speech':
          case 'application/futuresplash':
          case 'application/x-sprite':
          case 'application/x-sprite':
          case 'application/x-wais-source':
          case 'text/x-server-parsed-html':
          case 'application/streamingmedia':
          case 'application/vnd.ms-pki.certstore':
          case 'application/step':
          case 'application/sla':
          case 'application/vnd.ms-pki.stl':
          case 'application/x-navistyle':
          case 'application/step':
          case 'application/x-sv4cpio':
          case 'application/x-sv4crc':
          case 'image/vnd.dwg':
          case 'image/x-dwg':
          case 'application/x-world':
          case 'x-world/x-svr':
          case 'application/x-shockwave-flash':
          case 'application/x-troff':
          case 'text/x-speech':
          case 'application/x-tar':
          case 'application/toolbook':
          case 'application/x-tbook':
          case 'application/x-tcl':
          case 'text/x-script.tcl':
          case 'text/x-script.tcsh':
          case 'application/x-tex':
          case 'application/x-texinfo':
          case 'application/x-texinfo':
          case 'application/plain':
          case 'text/plain':
          case 'application/gnutar':
          case 'application/x-compressed':
          case 'image/tiff':
          case 'image/x-tiff':
          case 'image/tiff':
          case 'image/x-tiff':
          case 'application/x-troff':
          case 'audio/tsp-audio':
          case 'application/dsptype':
          case 'audio/tsplayer':
          case 'text/tab-separated-values':
          case 'image/florian':
          case 'text/plain':
          case 'text/x-uil':
          case 'text/uri-list':
          case 'text/uri-list':
          case 'application/i-deas':
          case 'text/uri-list':
          case 'text/uri-list':
          case 'application/x-ustar':
          case 'multipart/x-ustar':
          case 'application/octet-stream':
          case 'text/x-uuencode':
          case 'text/x-uuencode':
          case 'application/x-cdlink':
          case 'text/x-vcalendar':
          case 'application/vda':
          case 'video/vdo':
          case 'application/groupwise':
          case 'video/vivo':
          case 'video/vnd.vivo':
          case 'video/vivo':
          case 'video/vnd.vivo':
          case 'application/vocaltec-media-desc':
          case 'application/vocaltec-media-file':
          case 'audio/voc':
          case 'audio/x-voc':
          case 'video/vosaic':
          case 'audio/voxware':
          case 'audio/x-twinvq-plugin':
          case 'audio/x-twinvq':
          case 'audio/x-twinvq-plugin':
          case 'application/x-vrml':
          case 'model/vrml':
          case 'x-world/x-vrml':
          case 'x-world/x-vrt':
          case 'application/x-visio':
          case 'application/x-visio':
          case 'application/x-visio':
          case 'application/wordperfect6.0':
          case 'application/wordperfect6.1':
          case 'application/msword':
          case 'audio/wav':
          case 'audio/x-wav':
          case 'application/x-qpro':
          case 'image/vnd.wap.wbmp':
          case 'application/vnd.xara':
          case 'application/msword':
          case 'application/x-123':
          case 'windows/metafile':
          case 'text/vnd.wap.wml':
          case 'application/vnd.wap.wmlc':
          case 'text/vnd.wap.wmlscript':
          case 'application/vnd.wap.wmlscriptc':
          case 'application/msword':
          case 'application/wordperfect':
          case 'application/wordperfect':
          case 'application/wordperfect6.0':
          case 'application/wordperfect':
          case 'application/wordperfect':
          case 'application/x-wpwin':
          case 'application/x-lotus':
          case 'application/mswrite':
          case 'application/x-wri':
          case 'application/x-world':
          case 'model/vrml':
          case 'x-world/x-vrml':
          case 'model/vrml':
          case 'x-world/x-vrml':
          case 'text/scriplet':
          case 'application/x-wais-source':
          case 'application/x-wintalk':
          case 'image/x-xbitmap':
          case 'image/x-xbm':
          case 'image/xbm':
          case 'video/x-amt-demorun':
          case 'xgl/drawing':
          case 'image/vnd.xiff':
          case 'application/excel':
          case 'application/excel':
          case 'application/x-excel':
          case 'application/x-msexcel':
          case 'application/excel':
          case 'application/vnd.ms-excel':
          case 'application/x-excel':
          case 'application/excel':
          case 'application/vnd.ms-excel':
          case 'application/x-excel':
          case 'application/excel':
          case 'application/x-excel':
          case 'application/excel':
          case 'application/x-excel':
          case 'application/excel':
          case 'application/vnd.ms-excel':
          case 'application/x-excel':
          case 'application/excel':
          case 'application/vnd.ms-excel':
          case 'application/x-excel':
          case 'application/excel':
          case 'application/vnd.ms-excel':
          case 'application/x-excel':
          case 'application/x-msexcel':
          case 'application/excel':
          case 'application/x-excel':
          case 'application/excel':
          case 'application/x-excel':
          case 'application/excel':
          case 'application/vnd.ms-excel':
          case 'application/x-excel':
          case 'application/x-msexcel':
          case 'audio/xm':
          case 'application/xml':
          case 'text/xml':
          case 'xgl/movie':
          case 'application/x-vnd.ls-xpix':
          case 'image/x-xpixmap':
          case 'image/xpm':
          case 'image/png':
          case 'video/x-amt-showrun':
          case 'image/x-xwd':
          case 'image/x-xwindowdump':
          case 'chemical/x-pdb':
          case 'application/x-compress':
          case 'application/x-compressed':
          case 'application/x-compressed':
          case 'application/x-zip-compressed':
          case 'application/zip':
          case 'multipart/x-zip':
          case 'application/octet-stream':
          case 'text/x-script.zsh':
            isValid = true;
            break;
          default:
            isValid = false; // Or you can use the blob.type as fallback
            break;
        }
        if (isValid) {
          observer.next(null);
        } else {
          observer.next({ invalidMimeType: true });
        }
        observer.complete();
      });
      fileReader.readAsArrayBuffer(file);
    }
  );
  return frObs;
};
